### ISSUE TITLE
Allow passing callable into project app settings options and default value

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/sodar-core#1050]
(**NOTE** from @mikkonie: exact spec for issue can be seen below in comments.)

### Problem

The project settings allow to define valid options for String value. This is nice if all possible values are known beforehand. However, if the options are to come from the database, this is not enough.

### Solution

Allow users to pass in a callable function that is passed the current `Project` object and returns a Django model choices like list. That is, a list-like of values being list-likes of length 2. The first entry is the value (e.g., a UUID), the second a label to display in the UI.

### Alternative Solutions

N/A

### Additional Context

- bihealth/varfish-server#782

**Comment by mikkonie** [comment]
This sounds like a good idea, I'll think of the exact implementation.

This probably should be extended for default values for `PROJECT` and `PROJECT_USER` scopes as well, since those can also be dependent on the project in some cases.

**Comment by mikkonie** [comment]
## Spec

### Enable Callable for Default Value

- Add kwargs `project=None, user=None` to relevant `AppSettingAPI` methods `get_default()` and `get_defaults()`
    * These kwargs should go **before** `post_safe`
    * `post_safe` is only used for tests. This may break some tests if they provide `post_safe` as arg instead of kwargs, those can be easily fixed.
- Pass new kwargs where we use `get_default()` and `get_defaults()`
    * Especially in project and user forms
- In `get_default()`, add check for value in definition being a callable
    * If yes, call callable with `project` and `user` values
    * The actual expected arguments vary between setting scopes: `PROJECT` only needs project, `USER` only needs user and `PROJECT_USER` needs both. To simplify things, let's expect these methods always to take both arguments even if `None`.
- Add example app settings with callable for default value to `project_example_app`
    * One setting for each scope
    * Also add the method to call (you can use the same one for all of the example settings)
- Add tests for the example settings with callable default value in `projectroles.tests.test_app_settings`
- This may be a good time for requesting a review :)
    
### Enable Callable for Options

- Implement and test the default value first
- Add kwargs `project=None, user=None` to `validate()`
- Pass new kwargs in `set()`
- If options is callable, call with kwargs in `validate()`
- Add check for callable options in `forms.py` under `_set_app_setting_widget()`
    * Call options callable with project and user
- Add example app settings and tests as was done for the default value
- Implement support for lists of tuples returned from options in `_set_app_setting_widget()`
    * Returned result can be either list of strings/integers like currently..
    * ..or list of `[(value, label)]`
    * Pass to widget accordingly
- Test tuple options

This is a bit of a complex one so don't hesitate to ask if something's unclear or I made a mistake/omission.

**Comment by mikkonie** [comment]
Done by @gromdimon.
