### ISSUE TITLE
Timeline modal fails for extra data after viewing event details

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1055]
### Describe the Bug

In the `timeline` app, after opening the modal for event details, the same content remains visible when closing and reopening the modal for extra data.

### How to Reproduce

1. Open the modal for event details (via the link in event timestamp)
2. Close the modal
3. Open the modal for event extra data (via the extra data link on the right hand side of the event list)

### Expected Behavior

Extra data should be visible in the modal content instead of the event details.

### Screenshots

![timeline](https://user-images.githubusercontent.com/11211145/204860917-2ce48abc-83b2-4a6f-8dcc-4a23c1ef0b04.png)

**Comment by gromdimon** [comment]
Should be closed
