### ISSUE TITLE
Crash in timeline_site.html from missing plugin_lookup

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1076]
Viewing the site-wide timeline event list currently crashes due to a missing `plugin_lookup` dict.

To reproduce, create an event in `shell_plus` as follows:
```
from projectroles.plugins import get_backend_api
User = get_user_model()
timeline = get_backend_api('timeline_backend')
timeline.add_event(project=None, app_name='example_site_app', user=User.objects.first(), event_name='test_event', description='No project')
```
Next navigate to site-wide events and observe the crash.

This should be solvable by simply adding the following line: `{% get_plugin_lookup as plugin_lookup %}`

It should to be placed under the `projectroles` block. I recommend adding this right below `{% has_perm 'timeline.view_site_timeline' request.user project as can_view_timeline %}`.

Tests should be updated to catch this. Alas, let's skip that for now, as there are some changes expected to these templates in the near future (see #873).

**Comment by gromdimon** [comment]
- [x] Add line in template 
- [ ] Write a test

**Comment by mikkonie** [comment]
Fixed by @gromdimon
