### ISSUE TITLE
Add Python 3.11 support

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1157]
Once we upgrade to Django v4 (#880), we should also look into adding Python v3.11 support.

@gromdimon reports that he gave it a try in a work branch and it seemed to work fine in CI.

We still have to test this very carefully, see no dependencies raise issues and, preferrably, also test it out with systems like SODAR and Varfish in development.

As 3.11 also comes with some significant performance updates, we could also consider setting it as default version once updated. For that, see issue #903.

**Comment by gromdimon** [comment]
Here is successfull [attempt](https://github.com/gromdimon/sodar-core/actions/runs/4337872042)

**Comment by mikkonie** [comment]
Done.
