### ISSUE TITLE
Rename Alerts

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-core#1277]
### Problem
The term _Alert_ carries a very different meaning when talking about software engineering or the real world. Especially because of the red background and the blinking { ! } SODAR's alerts section conveys the meaning of "Something has gone wrong." imo.

![grafik](https://github.com/bihealth/sodar-core/assets/29800411/4e01c1f6-1279-4165-a2b5-6ca1abbf6cd2)

### Solution
Choose a more neutral term (and colour) for user notifications.

**Comment by mikkonie** [comment]
The terminology and colouring is basically standard for the vast majority of modern websites, so this will not be altered.

There will be tools to moderate what kind of "alerts" you receive at some point in the future.
