### ISSUE TITLE
Separate and standardize API versioning

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1278]
This was discussed in yesterday's planning session and I fully agree it should be done.

Tying the REST API versioning to the SODAR Core version made sense when development was started, but not so much any more as the API has long since stabilized and breaking changes are few and far between.

It was also be discussed to use semantic versioning for the API, which is a great idea. (The SODAR Core package will never use semantic versioning, because that's not how anything works regarding web server projects)

## Spec

- Separate API versioning from SODAR Core versioning
- Separate API versions for each app
- Separate API version for remote project sync
    * Only intended for communication between SODAR Core sites
    * Functionality depends on internal logic on both client and server side
- Use semantic versioning for the API
- Start from v1.0
- On breaking changes, support older versions where feasible
- Accept headers continue to be used, no version URL nonsense

## Notes

- Starting with this change, API changes (breaking or not) have to be clearly documented
    * Most likely need to maintain updates in both API docs AND in the major changes doc
    * Link to API doc from major changes doc to avoid unnecessary repetition
    * Add documentation requirement to the release checklist
- Deprecate old versioning schema in this version, remove support in v1.1
    * Return warning from API views if used
    * Same goes for SODAR

**Comment by mikkonie** [comment]
Needless to say, this also needs to be done with the SODAR API. I will open a separate ticket in that repo once we've agreed on the details and prioritization for SODAR Core.

**Comment by holtgrewe** [comment]
Sounds good to me. Maybe remote sync is not ready for 1.x time yet?

For context, here is the concept of "microversioning" in OpenStack:

- https://docs.openstack.org/senlin/ocata/developer/api_microversion.html

Here is a description of the -- central -- compute API microversioning

- https://docs.openstack.org/api-guide/compute/microversions.html

**Comment by mikkonie** [comment]
Done. Other related things such as improving documentation and possible changing of output to match some Amazon thingamajic should go under other issues.
