### ISSUE TITLE
Return full_title in ProjectSerializer

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/sodar-core#1314]
### Problem

The "full title path" is not returned by the project REST API. This would be useful to have.

### Solution

Return the "full title path", e.g. "Top Level Cat / Sub Cat / Project Title" in a property of the project REST API.

### Alternative Solutions

N/A

### Additional Context

N/A

**Comment by mikkonie** [comment]
Good catch, this should definitely be included as a read-only field. Will add in v1.0.

**Comment by mikkonie** [comment]
Done. Cleaned up projectroles API view tests while I was at it.
