### ISSUE TITLE
Update python installation utility script to support `python3.11`

### ISSUE THREAD

**Issue by gromdimon** [bihealth/sodar-core#1376]
### Problem

After https://github.com/bihealth/sodar-core/commit/be012e5536bacf8bfbfe95e3c930324edae0309b implementation sodar-core environment uses python3.11. However the installation script still refer to python3.8.

### Solution

Adapt utility sctipts to meet new environment requirements.

### Alternative Solutions
N/A

### Additional Context
N/A

**Comment by mikkonie** [comment]
Done by @gromdimon, merged.
