### ISSUE TITLE
Update postgres installation script to support `postgresql16`

### ISSUE THREAD

**Issue by gromdimon** [bihealth/sodar-core#1378]
### Problem

After https://github.com/bihealth/sodar-core/commit/be012e5536bacf8bfbfe95e3c930324edae0309b implementation sodar-core environment uses postgresql-16. However the installation script still refer to postgresql-11

### Solution

Adapt utility sctipts to meet new environment requirements.

### Alternative Solutions
N/A

### Additional Context
N/A

**Comment by mikkonie** [comment]
Done by @gromdimon, merged.
