### ISSUE TITLE
Expand data types in app plugin settings

### ISSUE THREAD

**Issue by stolpeo** [bihealth/sodar-core#1439]
### Problem

Currently, only `BOOLEAN`, `STRING` and `INTEGER` are allowed datatypes in the app settings of the app plugins.

### Solution

It would be nice to have more datatypes like `JSON` and `FLOAT`.

### Alternative Solutions

Store all other datatypes as `STRING` and convert.

**Comment by stolpeo** [comment]
@mikkonie also, is there a max string length for datatype `STRING`?

**Comment by mikkonie** [comment]
`JSON` is already there and has been since the beginning. As for `FLOAT`, good idea.

There is a maximum value of `255` for the value in the model. I'm not sure why though, this can definitely be lifted.

**Comment by mikkonie** [comment]
Adding the `FLOAT` type should be trivial, just some work needed in validating and testing. Is there an existing use case for this? That is, should I include it in the v1.0 milestone?

**Comment by stolpeo** [comment]
If JSON is available, the current use-case would be covered by that. Currently no need.

**Comment by stolpeo** [comment]
Editing SODAR core app settings is possible via the `AppSettingAPI`. This allows us to build an interface around that. The more complex `SiteApp` settings can receive a link-out.

```
from projectroles.app_settings import AppSettingAPI
app_settings = AppSettingAPI()
app_settings.get('app_name', 'setting_name', project_object)
```

**Comment by mikkonie** [comment]
Closing this issue, as all the questions appear to be solved. We can open a separate ticket for adding the `FLOAT` data type, if more need arises for it.
