### ISSUE TITLE
Replace ProjectUserTag with project/user specific AppSetting

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#321]
Since implemented #266, the `ProjectUserTag` model and related APIs have been useless and should finally be removed.

The model is currently only used to "star" a project in the project header UI. This can instead be done with a `PROJECT_USER` scope app setting, selectable on the UI exactly as now.

The tricky part will be to do the migration scripts: before the migration to remove the `ProjectUserTag` model, we need to have a migration which populates the `AppSetting` model with existing project starring setting values.

We should also document this in major changes as it is theoretically possible that some site using SODAR Core would have used this model for something else. I'm 99.9998% sure this hasn't happened though :)

## Spec

- First get to know app settings, if not familiar yet
    * [AppSettingAPI](https://sodar-core.readthedocs.io/en/dev/app_projectroles_api_django.html?highlight=app%20settings#app-settings)
    * [Projectroles app settings](https://sodar-core.readthedocs.io/en/dev/dev_core_resource.html?highlight=app%20settings#projectroles-app-settings)
- Define a new setting in `PROJECTROLES_APP_SETTINGS`
    * `name = project_star`
    * `scope = APP_SETTING_SCOPE_PROJECT_USER`
    * `default = False`
- Add new `projectroles` migration to populate settings according to existing `ProjectUserTag` objects
    * For each object, create a setting for the project & user using `AppSettingAPI`
    * For reverse code, delete all app settings where `app == projectroles`  and `name == project_star`
- Update `ProjectStarringAjaxView` to use app settings instead of `ProjectUserTag`
- Update usages of `get_tag_state()` accordingly
- Update view and UI tests as needed to fit this new functionality
- **Only after testing the aforementioned steps properly:**
    * Remove `projectroles.project_tags`
    * Remove `ProjectUserTag` model and make migrations
    * Update docs

**Comment by gromdimon** [comment]
### TODO:
- [ ] Change home template to show propper stars

**Comment by mikkonie** [comment]
Done by @gromdimon.
