### ISSUE TITLE
Prevent sending invites to local users if local users are disabled

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#616]
If local users are not allowed, we should also not allow sending invites to users not recognized in our LDAP setup.

## Spec

- Logic for denial
    * IF `PROJECTROLES_ALLOW_LOCAL_USERS==False`
    * AND `ENABLE_SAML==False`
    * AND email domain not in `AUTH_LDAP_USERNAME_DOMAIN`, `AUTH_LDAP2_USERNAME_DOMAIN` or `ALT_LDAP_DOMAINS`
    * THEN prevent creation of invite
- Where and how to implement this
    * Add check in `ProjectInviteForm.clean()`
    * Perform check, use `add_error()` on the `email`field
    * Error message should be *"Local users not allowed, email domain not recognized for LDAP users"*
- Add test(s) in `TestProjectInviteCreateView`

**Comment by gromdimon** [comment]
Noticed, that `PROJECTROLES_ALT_LDAP_DOMAINS` are not configured in `config.settings.base.py`. Maybe it was meant `LDAP_ALT_DOMAINS`?

**Comment by mikkonie** [comment]
Done by @gromdimon.
